# Generated by Django 3.2.14 on 2022-08-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityModels',
            fields=[
                ('id', models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='defense.addparticipant', to_field='personnel_id')),
                ('activity1', models.BooleanField()),
                ('activity2', models.BooleanField()),
                ('activity3', models.BooleanField()),
                ('activity4', models.BooleanField()),
                ('photo', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='defense.addparticipant', to_field='personnel_id')),
                ('name', models.CharField(max_length=200)),
                ('activity1', models.CharField(default='NP', max_length=200)),
                ('activity2', models.CharField(default='NP', max_length=200)),
                ('activity3', models.CharField(default='NP', max_length=200)),
                ('activity4', models.CharField(default='NP', max_length=200)),
                ('salute_angle', models.FloatField(default=0)),
                ('photo', models.ForeignKey(db_column='photo', on_delete=django.db.models.deletion.CASCADE, to='defense.activitymodels', to_field='photo')),
            ],
        ),
    ]
