# Generated by Django 3.2.14 on 2022-08-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodels',
            name='id',
            field=models.OneToOneField(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='defense.addparticipant', to_field='personnel_id'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='defense.addparticipant', to_field='personnel_id'),
        ),
    ]
