# Generated by Django 3.2.14 on 2022-08-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0002_auto_20220829_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.activitymodels', to_field='photo'),
        ),
    ]
