# Generated by Django 3.2.14 on 2022-08-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0003_alter_activityreport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
