# Generated by Django 3.2.14 on 2022-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0005_alter_activityreport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodels',
            name='photo',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='photo',
            field=models.TextField(),
        ),
    ]
